export const CAMP_LIST_REQUEST = 'CAMP_LIST_REQUEST';
export const CAMP_LIST_SUCCESS = 'CAMP_LIST_SUCCESS';
export const CAMP_LIST_FAIL = 'CAMP_LIST_FAIL';

export const CAMP_DETAILS_REQUEST = 'CAMP_DETAILS_REQUEST';
export const CAMP_DETAILS_SUCCESS = 'CAMP_DETAILS_SUCCESS';
export const CAMP_DETAILS_FAIL = 'CAMP_DETAILS_FAIL';

export const CAMP_CREATE_REQUEST = 'CAMP_CREATE_REQUEST';
export const CAMP_CREATE_SUCCESS = 'CAMP_CREATE_SUCCESS';
export const CAMP_CREATE_FAIL = 'CAMP_DETAILS_FAIL';

export const CAMP_CREATE_REVIEW_REQUEST = 'CAMP_CREATE_REVIEW_REQUEST';
export const CAMP_CREATE_REVIEW_SUCCESS = 'CAMP_CREATE_REVIEW_SUCCESS';
export const CAMP_CREATE_REVIEW_FAIL = 'CAMP_CREATE_REVIEW_FAIL';
export const CAMP_CREATE_REVIEW_RESET = 'CAMP_CREATE_REVIEW_RESET';

export const CAMP_DELETE_REQUEST = 'CAMP_DELETE_REQUEST';
export const CAMP_DELETE_SUCCESS = 'CAMP_DELETE_SUCCESS';
export const CAMP_DELETE_FAIL = 'CAMP_DELETE_FAIL';

export const CAMP_UPDATE_REQUEST = 'CAMP_UPDATE_REQUEST';
export const CAMP_UPDATE_SUCCESS = 'CAMP_UPDATE_SUCCESS';
export const CAMP_UPDATE_FAIL = 'CAMP_UPDATE_FAIL';
export const CAMP_UPDATE_RESET = 'CAMP_UPDATE_RESET';
